import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Content from '../component/Content/Content'
import Sidebar from '../component/Sidebar'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

 
      <div className={styles.container}>      
      <Content />
    </div>
    </>
  )
}
